title: Wut.Dev | Docs
description: Wut.Dev Documentation
theme: just-the-docs

url: https://wut.dev/docs

aux_links:
  Home: https://wut.dev
  App: https://app.wut.dev
  Blog: https://blog.wut.dev

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: light

footer_content: "Copyright 2025 • Wut.Dev"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: https://github.com/wut-dev/docs
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow

defaults:
  -
    scope:
      path: ""
    values:
      scripts:
        - /assets/js/external-links.js


# twitter:
#   username: WutDotDev
linkedin:
  username: company/wutdev
